# Generated by Django 5.2.1 on 2025-07-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='hero_images/default.jpg', upload_to='hero_images/')),
                ('countdown_date', models.DateTimeField()),
                ('featured_event_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_1', to='event.event')),
                ('featured_event_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_2', to='event.event')),
                ('featured_event_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_3', to='event.event')),
            ],
        ),
    ]
